update from sleirsgoevy/ps4jb branch:master context:Fixes: undefined reference to `__stack_chk_fail' (#66)
* Fixes: undefined reference to `__stack_chk_fail'

* Also adjust other Makefiles

Co-authored-by: Sergey Lisov <sleirsgoevy@gmail.com>